### ISSUE TITLE
ширина кнопок і картки

### ISSUE THREAD

**Issue by pecourses** [VasylUlianovskyi/JS-User-Card#1]
https://github.com/VasylUlianovskyi/JS-User-Card/blob/a800991a8438fce781345c0873bf8f7dd5b4c9cd/assets/css/style.css#L63
 - зараз фіксована ширина кнопок призводить до переповнення
![image](https://github.com/VasylUlianovskyi/JS-User-Card/assets/67504221/c7946887-963e-4208-b2f7-4f92d2340f52)
При звуженні картки проблема посилюється:
![image](https://github.com/VasylUlianovskyi/JS-User-Card/assets/67504221/71177943-c62a-4133-a6e5-098d8cb8db60)
Тому важливо уникати такої ширини дочірніх, яка призводитиме до переповнення. Тут було б зручно взагалі використовувати ширину, наприклад, по 48 відсотків, тоді 100-48*2=4% автоматом залишиться для відступа між кнопками. Тільки вони мають бути розташовані як space-between. І ще треба буде вказувати деяким контейнерам ставати на всю ширину (або через 100%, або наказати стретчитися), інакше кнопки все одно будуть вузькі (блокові елементи по дефолту займають всю ширину, а от з флекс-дітьми все залежить від налаштувань: якщо вони не стретчаться, то займуть стільки, скільки є контенту, тобто вужче).

**Comment by VasylUlianovskyi** [comment]
++
